# Generated by Django 4.2.4 on 2023-12-05 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocr',
            old_name='image_url',
            new_name='uploaded_image',
        ),
        migrations.AddField(
            model_name='ocr',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
