# Generated by Django 4.2.4 on 2023-12-06 16:31

from django.db import migrations, models
import ocr_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0002_rename_image_url_ocr_uploaded_image_ocr_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocr',
            name='uploaded_image',
            field=models.ImageField(upload_to=ocr_app.models.image_upload_path),
        ),
    ]
